// ---------------------------------------------------------------------------
// UI-only types — not generated by ts-rs.
// All domain types live in $lib/generated.
// ---------------------------------------------------------------------------

export type StoryBlock =
  | { kind: "narrator"; turn: number; text: string }
  | { kind: "player"; turn: number; text: string }
  | { kind: "opening"; text: string };

// ---------------------------------------------------------------------------
// Debug inspector types — track per-phase state using generated DebugEvent.
// All events arrive on the single "workshop:debug" Tauri event channel.
// ---------------------------------------------------------------------------

export const DEBUG_EVENT_CHANNEL = "workshop:debug";

export type PhaseStatus = "pending" | "processing" | "complete" | "skipped" | "error";

/**
 * Per-variant extract helpers. These match the generated DebugEvent
 * discriminated union variants from ts-rs.
 */
export type PredictionData = Extract<import("./generated").DebugEvent, { type: "prediction_complete" }>;
export type ContextData = Extract<import("./generated").DebugEvent, { type: "context_assembled" }>;
export type NarratorData = Extract<import("./generated").DebugEvent, { type: "narrator_complete" }>;
export type DecompositionData = Extract<import("./generated").DebugEvent, { type: "event_decomposed" }>;
export type ArbitrationData = Extract<import("./generated").DebugEvent, { type: "action_arbitrated" }>;
export type IntentData = Extract<import("./generated").DebugEvent, { type: "intent_synthesized" }>;
export type GoalsData = Extract<import("./generated").DebugEvent, { type: "goals_generated" }>;
export type ErrorData = Extract<import("./generated").DebugEvent, { type: "error" }>;

export interface DebugState {
  turn: number;
  phases: Record<string, PhaseStatus>;
  prediction: PredictionData | null;
  context: ContextData | null;
  decomposition: DecompositionData | null;
  arbitration: ArbitrationData | null;
  intent_synthesis: IntentData | null;
  goals: GoalsData | null;
  narrator: NarratorData | null;
  error: ErrorData | null;
}

// ---------------------------------------------------------------------------
// Structured log streaming — events arrive on "workshop:logs" channel.
// ---------------------------------------------------------------------------

export const LOG_EVENT_CHANNEL = "workshop:logs";

// ---------------------------------------------------------------------------
// Gameplay event streaming — events arrive on "workshop:gameplay" channel.
// All variants are server → client. The play view listens to drive prose
// streaming, phase indicators, and turn lifecycle transitions.
// ---------------------------------------------------------------------------

export const GAMEPLAY_CHANNEL = "workshop:gameplay";

export type GameplayEvent =
  | { kind: "SceneReady"; scene_id: string; title: string; setting_summary: string; cast_names: string[]; player_character: string; player_intent: string | null }
  | { kind: "InputReceived"; turn: number }
  | { kind: "ProcessingUpdate"; phase: string }
  | { kind: "NarratorProse"; chunk: string; turn: number }
  | { kind: "NarratorComplete"; prose: string; turn: number }
  | { kind: "TurnComplete"; turn: number; ready_for_input: boolean };
