"""Intersection schemas.

Defines the data structures for cross-domain synthesis outputs — the results
of an LLM examining how genre and spatial data interact, enrich each other,
and reveal gaps. Intersection synthesis is the core output of the B.3 pipeline.
"""

from pydantic import BaseModel

from narrative_data.schemas.shared import NarrativeEntity


class UpstreamRef(BaseModel):
    """A reference to an upstream entity that contributed to a synthesis.

    Upstream refs form the provenance chain for intersection outputs — they
    identify which genre and spatial entities were the inputs to the synthesis,
    with content digests to detect staleness.
    """

    entity_id: str
    """Entity ID of the upstream entity."""

    content_digest: str
    """Content hash of the upstream entity at synthesis time (for staleness detection)."""

    domain: str
    """The domain this entity belongs to: 'genre', 'spatial', etc."""


class Enrichment(BaseModel):
    """A synthesis-derived enrichment to an existing entity.

    Enrichments are additions to existing entities that emerge from cross-domain
    synthesis — insights that could not be derived from a single domain alone.
    They are not modifications; they are additions with explicit provenance.
    """

    target_entity_id: str
    """Entity ID of the entity being enriched."""

    enrichment_type: str
    """Category of enrichment: 'tonal_refinement', 'narrative_function', 'sensory_layer', etc."""

    content: str
    """The enrichment content — prose insight or structured addition."""


class IntersectionSynthesis(NarrativeEntity):
    """The output of cross-domain synthesis between genre and spatial entities.

    An intersection synthesis examines how specific genre regions and place
    entities interact — how the genre transforms the place, what tensions emerge,
    what gaps the combination reveals. This is the B.3 pipeline's primary output.
    """

    upstream_refs: list[UpstreamRef]
    """References to the upstream genre and spatial entities that were synthesised."""

    content_hash: str
    """Combined content hash of all upstream refs, for cache invalidation."""

    enrichments: list[Enrichment]
    """Enrichments to upstream entities derived from the synthesis."""

    gaps_identified: list[str]
    """Prose descriptions of gaps the synthesis reveals (missing data, unexplored angles)."""

    new_entries: list[str] = []
    """Entity IDs of new entities generated by this synthesis (if any)."""
