name: "Setup Rust Build Cache"
description: "Restores Rust build cache with consistent keys across CI workflows"

inputs:
  cache-prefix:
    description: "Cache key prefix for different workflow types"
    required: false
    default: "build"

runs:
  using: "composite"
  steps:
    - name: Restore Rust build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ inputs.cache-prefix }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ inputs.cache-prefix }}-
          ${{ runner.os }}-cargo-
